FROM scratch AS ctx

COPY --chmod=0755 build.sh /
COPY --chmod=0755 cleanup.sh /

FROM quay.io/fedora/fedora-bootc:latest

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/build.sh && /ctx/cleanup.sh

RUN bootc container lint
