name: jharmison-redhat | podman push zstd:chunked
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    
      - name: Checkout action
        uses: actions/checkout@v6
        
#      - name: Login to ghcr.io
#        uses: redhat-actions/podman-login@v1
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#

      - name: Compare layers with previous build
        run: |
          OLD=$(skopeo inspect --raw docker://ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}-plugin:latest 2>/dev/null | jq -r '[.layers[].digest]' || echo "[]")
          

      - name: Build, rechunk, and push
        uses: jharmison-redhat/action-bootc-build@v1
        with:
          file: containerfile-base
          tag: ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}-plugin-push:latest
          push: "false"
          max-layers: 128

      - name: Push image
        run: |
          sudo podman push \
            --compression-format zstd:chunked \
            --compression-level 12 \
            --force-compression \
            --creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} \
            ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}-plugin-push:latest

      - name: Compare layers with previous build
        run: |
          NEW=$(skopeo inspect --raw docker://ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}-plugin:latest | jq -r '[.layers[].digest]')
          echo "Changed layers: $(diff <(echo $OLD | jq -r '.[]') <(echo $NEW | jq -r '.[]') | grep -c '^[<>]')"
