name: bootc-image-plugin
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    
      - name: Checkout action
        uses: actions/checkout@v6

      - name: Login to ghcr.io
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compare layers with previous build
        run: |
          OLD=$(skopeo inspect --raw docker://ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}-niri:latest 2>/dev/null | jq -r '[.layers[].digest]' || echo "[]")
          

      - name: Build, rechunk, and push
        uses: jharmison-redhat/action-bootc-build@v1
        with:
          file: containerfile-niri
          tag: ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}-plugin:latest
          push: "true"
          max-layers: 128
