name: basic build niri
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
env:
  tag: niri
  file: Containerfile-{{ env.env }}
  repo: ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}-{{ env.env }}:latest
jobs: 
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout action
      uses: actions/checkout@v6
    - name: Build image
      run: |
        podman build \
          -f ${{ env.file }} \
          -t ${{ env.repo }} .

#    - name: Rechunk image with chunkah
#      run: |
#        # Export rootfs as a flat directory
#        CONTAINER=$(podman create ${{ env.repo }})
#        mkdir -p /tmp/rootfs
#        podman export $CONTAINER | tar -xC /tmp/rootfs
#        podman rm $CONTAINER
#
#        # Capture image config for label/metadata preservation
#        export CHUNKAH_CONFIG_STR="$(podman inspect ${{ env.repo }})"
#
#        # Rechunk: mount the rootfs dir into /chunkah, pipe OCI archive back in
#        podman run --rm \
#          -v /tmp/rootfs:/chunkah:ro \
#          --security-opt=label=disable \
#          -e CHUNKAH_CONFIG_STR \
#          quay.io/coreos/chunkah build \
#            --max-layers 128 \
#            --skip-special-files \
#            --prune /sysroot/ \
#            -t ${{ env.repo }} | podman load
#
#        # Clean up
#        rm -rf /tmp/rootfs
#
#    - name: Push image
#      run: podman push --creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} ${{ env.repo }}


    - name: Rechunk image with chunkah
      run: |
        mkdir -p /tmp/rootfs
        podman export $(podman create --name rechunk ${{ env.repo }}) | tar -xC /tmp/rootfs
        podman rm rechunk
        CHUNKAH_CONFIG_STR="$(podman inspect ${{ env.repo }})" \
        podman run --rm \
          -v /tmp/rootfs:/chunkah:ro \
          --security-opt=label=disable \
          -e CHUNKAH_CONFIG_STR \
          quay.io/coreos/chunkah build --max-layers 128 --skip-special-files --prune /sysroot/ \
            -t ${{ env.repo }} | podman load

    - name: Push image
      run: |
        podman push \
          --compression-format zstd:chunked \
          --creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} \
          ${{ env.repo }}




