name: bootc-image-plugin-push
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    
      - name: Checkout action
        uses: actions/checkout@v6
        
#      - name: Login to ghcr.io
#        uses: redhat-actions/podman-login@v1
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
      - name: Build, rechunk, and push
        uses: jharmison-redhat/action-bootc-build@latest
        with:
          file: Containerfile-niri
          tag: ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}-plugin-push:latest
          push: "false"
          max-layers: 128

      - name: Push image
        run: |
          sudo podman push \
            --compression-format zstd:chunked \
            --compression-level 12 \
            --force-compression \
            --creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} \
            ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}-plugin-push:latest
