name: basic build niri
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
env:
  tag: ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}-niri:latest
jobs: 
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout action
      uses: actions/checkout@v6
    - name: Build image
      run: podman build -f Containerfile-niri -t ${{ env.tag }} .
    - name: Rechunk image with chunkah
      run: |
        export CHUNKAH_CONFIG_STR="$(podman inspect ${{ env.tag }})"
        podman save ${{ env.tag }} -o /tmp/original.tar
        podman run --rm \
          -v /tmp/original.tar:/chunkah.tar:ro \
          -e CHUNKAH_CONFIG_STR \
          quay.io/coreos/chunkah build \
            --from oci-archive:/chunkah.tar \
            --max-layers 128 \
            -t ${{ env.tag }} | podman load
    - name: Push image
      run: podman push --creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} ${{ env.tag }}
